[tool.poetry]
name = "10-2-git"
version = "0.1.0"
description = ""
authors = ["Alexandra <a.chigrina89@gmail.com>"]
readme = "README.md"
packages = [{include = "10"}]

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
